PracticeCrudUsingEF/Controllers/NameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PracticeEF.DbCtx;
using PracticeEF.Models;
using System.Data.Entity;
using System.ComponentModel;
using OfficeOpenXml;

namespace PracticeEF.Controllers
{
    [Authorize]
    public class NameController : Controller
    {
        // GET: Name
        public ActionResult Names()
        {
            MukeshDb db = new MukeshDb();
            //var res = db.Friends.ToList();
            var res = db.GetData().ToList();
            List<NameModel> list = new List<NameModel>();
            foreach (var item in res)
            {
                list.Add(new NameModel()
                {
                    Id = item.Id,
                    Name = item.Name,
                });
            }

            ViewBag.List = "list";
            return View(list);
        }

        public ActionResult Delete(int id)
        {
            MukeshDb db = new MukeshDb();

            /*var res = db.Friends.Where(m => m.Id == id).FirstOrDefault();
            if (res != null)
            {
                db.Friends.Remove(res);
                db.SaveChanges();
            }*/

            var res = db.DeleteData(id);
            return RedirectToAction("Names");
        }

        /*public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(NameModel m)
        {
            if(ModelState.IsValid)
            {
                MukeshDb db = new MukeshDb();
                db.Friends.Add(new Friend
                {
                    Name = m.Name
                });
                db.SaveChanges();
            }
            return RedirectToAction("Names");
        }

        public ActionResult Edit(int id)
        {
            MukeshDb db = new MukeshDb();
            var res = db.Friends.Where(f => f.Id == id).FirstOrDefault();

            var m = new NameModel
                {
                    Id = res.Id,
                    Name = res.Name
                };

            return View(m);
        }

        [HttpPost]
        public ActionResult Edit(NameModel m)
        {
            if(ModelState.IsValid)
            {
                MukeshDb db = new MukeshDb();
                var res = db.Friends.Where(f => f.Id == m.Id).FirstOrDefault();
                if(res != null)
                {
                    res.Name = m.Name;
                    db.SaveChanges();
                }
            }
            return RedirectToAction("Names");
        }*/

        /*public ActionResult CreateOrEdit(int? id)
        {
            var m = new NameModel();
            if(id.HasValue)
            {
                MukeshDb db = new MukeshDb();
                var res = db.Friends.Where(f => f.Id == id).FirstOrDefault();
                if(res != null)
                {
                    m.Id = res.Id;
                    m.Name = res.Name;
                }
            }
            return View(m);
        }

        [HttpPost]
        public ActionResult CreateOrEdit(NameModel m)
        {
            if(ModelState.IsValid)
            {
                MukeshDb db = new MukeshDb();
                if(m.Id.HasValue)
                {
                    var res = db.Friends.Where(f => f.Id == m.Id).FirstOrDefault();
                    if(res != null)
                    {
                        res.Name = m.Name;
                    }
                }
                else
                {
                    db.Friends.Add(
                        new Friend
                        {
                            Name = m.Name
                        });
                }
                db.SaveChanges();
                return RedirectToAction("Names");
            }
            return View(m);
        }*/

        public ActionResult Edit(int id)
        {
            MukeshDb db = new MukeshDb();
            var res = db.Friends.Where(f => f.Id == id).FirstOrDefault();
            NameModel m = new NameModel();
            if (res != null)
            {
                m.Id = res.Id;
                m.Name = res.Name;
            }
            ViewBag.Name = "Edit";
            return View("Create", m);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(NameModel m)
        {
            MukeshDb db = new MukeshDb();
            /*Friend f = new Friend();
            f.Id = m.Id;
            f.Name = m.Name;
            if (m.Id == 0)
            {
                db.Friends.Add(f);
                db.SaveChanges();
            }
            else
            {
                db.Entry(f).State = EntityState.Modified;
                db.SaveChanges();
            }*/

            if(m.Id == 0)
            {
                db.InsertData(m.Name);
            }
            else
            {
                db.UpdateData(m.Id, m.Name);
            }
            return RedirectToAction("Names");
        }

        public ActionResult ExportToExcel()
        {
            MukeshDb db = new MukeshDb();
            var data = db.Friends.ToList();

            ExcelPackage.LicenseContext = OfficeOpenXml.LicenseContext.NonCommercial; // Set license context

            using (ExcelPackage package = new ExcelPackage())
            {
                ExcelWorksheet worksheet = package.Workbook.Worksheets.Add("Names");

                // Add column headers
                worksheet.Cells[1, 1].Value = "Id";
                worksheet.Cells[1, 2].Value = "Full Name";

                // Add data
                int row = 2;
                foreach (var item in data)
                {
                    worksheet.Cells[row, 1].Value = item.Id;
                    worksheet.Cells[row, 2].Value = item.Name;
                    row++;
                }

                // Save the file
                byte[] fileContents = package.GetAsByteArray();
                return File(fileContents, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Names.xlsx");
            }
        }
    }
}

PracticeCrudUsingEF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Friends", "Names", "Name", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Add Friends", "Create", "Name", new { area = "" }, new { @class = "nav-link" })</li>
                    @if (Session["UserId"] != null) // Check if user is logged in
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                @Html.ActionLink("Logout", "Logout", "Auth", null, new { @class = "nav-link" })
                            </li>
                        </ul>
                    }
                    @if(ViewBag.List == "list")
                    {
                        <li class="nav-item">
                            @Html.ActionLink("ExportToExcel", "ExportToExcel", "Name", null, new { @class = "nav-link" })
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>