Models/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SocialMediaWebApp.Models
{
    public class Login
    {
        [Required(ErrorMessage = "Username is required")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Password is required")]
        public string Password { get; set; }
    }
}

Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SocialMediaWebApp.Models
{
    public class Post
    {
        public int PostId { get; set; }
        public int UserId { get; set; }

        [Required(ErrorMessage = "Post content is required")]
        public string PostContent { get; set; }

        public DateTime PostTime { get; set; }
    }
}

Models/Users.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SocialMediaWebApp.Models
{
    public class Users
    { 
        public int UserId { get; set; }

        [Required(ErrorMessage = "Username is required")]
        [StringLength(50, MinimumLength = 6,ErrorMessage = "Username must be between 6 and 50 characters")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Password is required")]
        [StringLength(100, MinimumLength = 6, ErrorMessage = "Password must be at least 6 characters")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Email is required")]
        [EmailAddress(ErrorMessage = "Invalid email format")]
        [StringLength(100, ErrorMessage = "Email cannot exceed 100 characters")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Full name is required")]
        [StringLength(100, ErrorMessage = "Full name cannot exceed 100 characters")]
        public string FullName { get; set; }

        public DateTime RegistrationDate { get; set; }
    }
}

Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SocialMediaWebApp.Controllers
{
    public class ErrorController : Controller
    {
        // GET: Error
        public ActionResult Error()
        {
            Response.StatusCode = 404;
            return View("Error");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SocialMediaWebApp.Controllers
{
    public class HomeController : Controller
    {
        DataAccessLayer dal = new DataAccessLayer();

        // GET: Home
        public ActionResult Index()
        {
            int userId = Session["UserId"] != null ? (int)Session["UserId"] : 0;//retrive the userid from login
            var homePagePosts = dal.GetHomePagePosts();

            ViewBag.UserId = userId;//store userid in viewbag
            return View(homePagePosts);
        }
    }
}

Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SocialMediaWebApp.Models;

namespace SocialMediaWebApp.Controllers
{
    public class PostController : Controller
    {
        DataAccessLayer dal = new DataAccessLayer();

        // GET: Post/Create
        public ActionResult Create(int userId)
        {
            ViewBag.UserId = userId;//retrive from homepage

            return View();
        }

        [HttpPost]
        public ActionResult Create(Post p, int userId)
        {
            if(ModelState.IsValid)
            {
                p.UserId = userId;

                dal.CreatePost(p);

                Session["UserId"] = userId;

                return RedirectToAction("Index","Home");
            }
            return View(p);
        }

        [HttpPost]
        public ActionResult Delete(int postId, int userId)
        {
            dal.DeletePostFromHomePage(postId, userId);
            return RedirectToAction("Index","Home");
        }
    }
}

Controllers/UserLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using SocialMediaWebApp.Models;
using Login = SocialMediaWebApp.Models.Login;

namespace SocialMediaWebApp.Controllers
{
    public class UserLoginController : Controller
    {
        DataAccessLayer dal = new DataAccessLayer();
        // GET: UserLogin
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Login l)
        {
            if(ModelState.IsValid)
            {
                Users user = new Users
                {
                    Username = l.Username,
                    Password = l.Password
                };
                int userId = dal.LoginUser(user);
                    if(userId != 0)
                    {
                        Session["UserId"] = userId;//store id for future use in homepage

                        return RedirectToAction("Index","Home");
                    }
            }
            return View("Login",l);
        }
    }
}

Controllers/UserProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SocialMediaWebApp.Controllers
{
    public class UserProfileController : Controller
    {
        DataAccessLayer dal = new DataAccessLayer();

        // GET: UserProfile
        public ActionResult Profile(int userId)
        {
            var userProfile = dal.GetUserProfile(userId);
            return View(userProfile);
        }
    }
}

Controllers/UserRegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SocialMediaWebApp.Models;

namespace SocialMediaWebApp.Controllers
{
    public class UserRegistrationController : Controller
    {
        DataAccessLayer dal = new DataAccessLayer();

        // GET: UserRegistration
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(Users u)
        {
            if(ModelState.IsValid)
            {
                dal.RegisterUser(u);
                return RedirectToAction("Login","UserLogin");
            }
            return View();
        }
    }
}

Views/UserRegistration/Register.cshtml
@model SocialMediaWebApp.Models.Users

@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header text-center">User Registration</div>
                <div class="card-body">
                    @using (Html.BeginForm("Register", "UserRegistration", FormMethod.Post, new { @class = "form"}))
                    {
                        <div class="d-flex flex-column align-items-center">
                            <div class="mb-3">
                                @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "form-label" })
                                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                            </div>

                            <div class="mb-3">
                                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "form-label" })
                                @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>

                            <div class="mb-3">
                                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "form-label" })
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>

                            <div class="mb-3">
                                @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "form-label" })
                                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                            </div>
                        </div>


                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Register</button>
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>
</div>